export const SET_CLIENT = "SET_CLIENT";
export const SET_ERROR = "SET_ERROR";

export const SET_ACTIVE_USERS = "SET_ACTIVE_USERS";
export const ADD_ACTIVE_USER = "ADD_ACTIVE_USER";
export const DELETE_ACTIVE_USER = "DELETE_ACTIVE_USER";

export const GET_LOCATION_RESPONSES = "GET_LOCATION_RESPONSES";
export const ADD_LOCATION_RESPONSE = "ADD_LOCATION_RESPONSE";
export const DELETE_LOCATION_RESPONSE = "DELETE_LOCATION_RESPONSE";
export const SET_CHOSEN_LOCATION_RESPONSE = "SET_CHOSEN_LOCATION_RESPONSE";